SELECT p.PLAYER_NAME
	, p.SEASON
	, t.ABBREVIATION
	, t.NICKNAME
FROM NBADataAnalysis.dbo.players p
INNER JOIN NBADataAnalysis.dbo.teams t
ON p.TEAM_ID = t.TEAM_ID
WHERE 1=1
	AND p.SEASON = 2019
	AND t.ABBREVIATION = 'CHI'
ORDER BY p.PLAYER_ID